version: '2'

services:
  main:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "2222:22"
      - "8080:8080"
      - "9000:9000"
    environment:
      - EDITOR=vim
    volumes:
      - ./hw2:/home/cn/hw2
    privileged: true
    networks:
        default:

networks:
    default:

